YangCatalog/module-compilation

bin/cronjob-daily
bin/cronjob-weekly
bin/job_log.py

Log result of cronjob to JSON file

---

bin/cronjob-daily
bin/cronjob-weekly
bin/job_log.py

Logging results of cronjobs to JSON file fixed

---

Dockerfile

YumaPro client update to version 19.10-12

---

bin/runYANGgenericstats-daily.sh
bin/runYANGgenericstats-weekly.sh
bin/yangGeneric.py
bin/yangIetf.py

Updated way of getting all the modules data

---

bin/runYANGgenericstats-weekly.sh
bin/yangGeneric.py
bin/yangIetf.py

Changes to cronjob-weekly to make it possible to run more in parallel

---

bin/runYANGgenericstats-weekly.sh
bin/rundownloadgithub.sh
requirements.txt

Missing PIDs array declaration

---

bin/runYANGgenericstats-daily.sh
bin/runYANGgenericstats-weekly.sh

Speed up processing Juniper modules

---

bin/resources/index.html

Fixed index.html to correctly list Cisco IOS-XE results

---

bin/gatherIETFdependentModules.py
bin/runYANGgenericstats-daily.sh
crontab

Changes to cronjob-daily to make it possible to run more in parallel

---

Dockerfile
requirements.txt

- payng update to version 2.4.0
- YumaPro client link to the newest version file
- requests lib unified through all YangCatalog apps

Pyang update + YumaPro client update to version 20.10-3

---

Dockerfile

Confd update to version 7.5

---

CHANGELOG.md
bin/runYANGgenericstats-daily.sh
bin/runYANGgenericstats-weekly.sh

--silent argument added to suppress progress messages
This resolves #58 

Hide cURL progress meter or error messages

---

CHANGELOG.md
requirements.txt

xym tool update to version 0.5

---

bin/runYANGgenericstats-daily.sh

- directory named as git branch added to path
This resolves #63 

OpenROADM directory structure extended with version

---

bin/cronjob-weekly
bin/fileHasher.py
bin/runIETFstats.sh
bin/runYANGgenericstats-daily.sh
bin/runYANGgenericstats-weekly.sh
bin/versions.py
bin/yangGeneric.py
bin/yangIetf.py
crontab

- New class create in versions.py file
- Methods that received versions have been removed
- Hashing file content and storing hash value to json file
- Hash of file consist of content of the file and used validators
- Compare hashes before running module compilation
- Skipping compilation if module has not changed
- Load compilation results from previous cronjob run
- cronjob-daily will now run as a part of cronjob weekly
This resolves #55 

Files content hashing

---

bin/runYANGgenericstats-weekly.sh

Quickfix: Fixed rootdir path for Juniper 14.2

---

CHANGELOG.md
Dockerfile

Update YumaPro validator to version 20.10-6

---

CHANGELOG.md
bin/yangGeneric.py
bin/yangIetf.py

- JSON dictionaries rewriten each time - unnecessary modules are properly removed from JSON files

Remove unnecessary modules from JSON files everytime

---

.gitignore
bin/runYANGgenericstats-daily.sh
bin/runYANGgenericstats-weekly.sh

Limit number of processes spawned to optimize RAM memory load

---

bin/fileHasher.py
requirements.txt

Fix: FileLock added for protected access to hashes JSON file

---

bin/generatePrivatePage.py

Signed-off-by: Kovac <miroslav.kovac@pantheon.tech>

generate json for new ui

---

Dockerfile

mailname changed to yangcatalog.org

---

bin/resources/index.html
bin/runYANGgenericstats-weekly.sh

Functionality adjustments to parse Cisco SVO models

---

bin/yangGeneric.py
bin/yangIetf.py

Parsing modules which have compilation result None again

---

Dockerfile
bin/cronjob
bin/generatePrivatePage.py
bin/runYANGgenericstats.sh
bin/yangGeneric.py
bin/yangIetf.py
conf/paths.sh

Problem with UnicodeDecodeError fixed

---

CHANGELOG.md
bin/yangGeneric.py
bin/yangIetf.py

Modules compilation status/result overwriting fixed

---

bin/yangIetf.py

IETFYANGRFC.json file generating fixed

---

bin/extract_emails.py
bin/resources/compilationStatusTemplate.html
bin/yangIetf.py

This resolves #99 
- Yang labels changed for capital YANG
- Title changed to: **YANG Validation Results** as proposed

Title changed for HTML page containing compilation result

---

bin/redisConnections/redisConnection.py
bin/yangIetf.py
requirements.txt

Patch modules data also in Redis

---

bin/checkArchivedDrafts.py
bin/extractors/dratfExtractor.py
bin/job_log.py
bin/messageFactory/messageFactory.py
bin/remove_directory_content.py
bin/yangIetf.py
crontab

- Once a week extract all modules from all archived drafts and check
whether extracted yang modules are stored in YANG Catalog
- Send email notification if any modules are missing
- Copy extracted missing modules into separate directory
for possible usage e.x: populate.py script
This resolves #106

Check archived drafts for missing modules

---

bin/checkArchivedDrafts.py
bin/cronjobs/cronjob-drafts
bin/messageFactory/messageFactory.py
bin/redisConnections/redisConnection.py
bin/runIETFstats.sh
bin/yangIetf.py

- email body updated
- runIETFstats.sh script formatted
- reload cache added to runIETFstats.sh script

Edit body of an email that notifies of missing modules

---

bin/parsers/confdcParser.py
bin/parsers/pyangParser.py
bin/yangGeneric.py
bin/yangIetf.py

Remove absolute paths from validators output

---

bin/filesGenerator.py
bin/runIETFstats.sh
bin/yangGeneric.py
bin/yangIetf.py

- every saturday cronjob will run yangIetf.py script over my-id-archive-mirror directory instead of my-id-mirror dir

Run yangIetf.py over all the archived drafts once a week

---

bin/extract_emails.py

- Code refactored
- For cycles simpilied with list comprehensions

extract_emails.py script refactored

---

bin/fileHasher.py
bin/filesGenerator.py
bin/yangIetf.py

- compilation functionality moved into separate classes
- should_parse() method added to the fileHasher

yangIetf.py script refactored

---

bin/parsers/confdcParser.py
bin/parsers/pyangParser.py
bin/parsers/yanglintParser.py
bin/resources/index.html

Double newlines in compilation-results

---

bin/resources/index.html
bin/runYANGgenericstats.sh
bin/rundownloadgithub.sh

- master branch was renamed to main
- URLs to github updated for Cisco

Changes after renaming YangModels/yang main branch

---

requirements.txt

Pyang update to version 2.5.3

---

.gitignore
.vscode/settings.json

Remove .vscode from .gitignore

---

bin/checkArchivedDrafts.py
bin/compilators/draftsCompilator.py
bin/compilators/rfcsCompilator.py
bin/gatherIETFdependentModules.py
bin/parsers/yangdumpProParser.py
bin/utility/utility.py
bin/yangGeneric.py
bin/yangGetStats.py
bin/yangIetf.py

Code adjustments after config file update

---

bin/parsers/yangdumpProParser.py
bin/parsers/yanglintParser.py
bin/runYANGgenericstats.sh

- duplicate messages removed from yanglint and yangdump-pro parsers

Remove duplicate messages from validators output

---

bin/generatePrivatePage.py
bin/resources/index.html
bin/runGenerateFiguresAndStats.sh
bin/runYANGgenericstats.sh

Compilation of multiple ETSI directories added

---

bin/checkArchivedDrafts.py
bin/extract_emails.py
bin/extractors/dratfExtractor.py
bin/get_config.py
bin/remove_directory_content.py
bin/rename-file-backup.py
bin/runGenerateFiguresAndStats.sh
bin/yang-exclude-bad-drafts.py
bin/yangGeneric.py
bin/yangGetStats.py
bin/yangIetf.py
bin/yangVersion11.py

Python scripts arguments updates

---

bin/extractors/dratfExtractor.py
bin/yangIetf.py

- create json file containing IETF drafts name which have
problem with extracting module code using xym extractor

Create list of problematic IETF drafts

---

bin/checkArchivedDrafts.py
bin/compilators/draftsCompilator.py
bin/compilators/rfcsCompilator.py
bin/gatherIETFdependentModules.py
bin/messageFactory/messageFactory.py
bin/utility/utility.py
bin/yangGeneric.py
bin/yangIetf.py

- URL prefixes are now rather loaded from a config file than created
in the code
- Now these prefixes can be updated in single place - in the config file

Loading URL prefixes from a config file

---

bin/utility/utility.py

Save compilation results to a file even if the module isn't
present in redis yet.

feat: always save compilation result files

---

bin/yang_version_1_1.py
tests/resources/test.conf
tests/resources/yang_version_1_1/YANG/test.yang
tests/test_yang_version_1_1.py

test: unit tests covering yang_version_1_1.py

---

bin/rename_file_backup.py
tests/resources/test.conf
tests/test_rename_file_backup.py

test: unit tests covering rename_file_backup.py

---

bin/remove_directory_content.py
tests/test_remove_directory_content.py

test: unit tests covering remove_directory_content.py

---

bin/check_archived_drafts.py
bin/cronjobs/cronjob-drafts
bin/extract_ietf_modules.py
bin/extractors/dratf_extractor.py
bin/job_log.py
tests/test_rename_file_backup.py

fix: minor changes to check_archived_drafts.py script

---

bin/gather_ietf_dependent_modules.py
tests/resources/gather_ietf_dependent_modules/all_modules/ietf-test@2022-08-01.yang
tests/resources/gather_ietf_dependent_modules/payloads.json
tests/test_gather_ietf_dependent_modules.py

test: unit tests covering gather_ietf_dependent_modules.py

---

bin/utility/static_variables.py
bin/utility/utility.py

fix: handle error returned from pyang fbasic-info

---

bin/run_ietf_module_extraction.sh
bin/run_module_compilation.sh

Signed-off-by: SlavomirMazurPantheon <slavomir.mazur@pantheon.tech>

chore: fetching draft*.xml files using rsync

---

bin/yang_get_stats.py

fixed an edge-case in ```yang_get_stats.py``` script, refactored this script, after running it for the first time I got this output: 
it seems like everything is okay now (not sure about ```cannot stat``` errors in the end)
resolves #204

Fix yang get stats script

---

.vscode/launch.json
Dockerfile
requirements.txt

Signed-off-by: SlavomirMazurPantheon <slavomir.mazur@pantheon.tech>

build: load xym tool version from .env file

---

bin/compile_modules.py
bin/parsers/confdc_parser.py
bin/parsers/pyang_parser.py
bin/parsers/yang_parser.py
bin/parsers/yanglint_parser.py
bin/utility/utility.py

Replaced ```pypy3 -fbasic-info``` with YangParser, and did some minor refactoring.
NOTE: Couldn't reproduce the bug either but everything seems working fine with my changes as well, so I think it might resolve the bug in production.
resolves #209

fix: fixed parsing of modules with pypy3, replaced parsing by using pyang directly

---

bin/check_archived_drafts.py
bin/extractors/helper.py

Removed missing modules starting with empty string from email messages

Fix check archived drafts script

---

.config/matplotlib/matplotlibrc
.gitignore
bin/symd.py

Signed-off-by: SlavomirMazurPantheon <slavomir.mazur@pantheon.tech>

fix: matplotlibrc file added

---

Dockerfile
crontab

fix: set VIRTUAL_ENV in cron environment

---

Dockerfile
conf/paths.sh
cronjobs/cronjob-daily
cronjobs/run_download_github.sh
crontab
extractors/draft_extractor.py
figures_and_stats/run_generate_figures_and_stats.sh
ietf_modules_extraction/run_ietf_module_extraction.sh
lint_requirements.txt
main_page_generation/run_generate_main_page.sh
modules_compilation/run_module_compilation.sh
resources/HTML/HTML.py
utility/pyang_plugin/json_tree.py

I fixed environment variables for crontab
resolves #254

fix: fixed environment variables for cron

---

modules_compilation/compile_modules.py

Refactored the ```compile_modules.py``` script, so for now it's divided into five separate classes that inherit from the base class and override some logic, so it's easier to change something in some specific classes and all the if elif statements are gone
resolves #262

refactor: refactored compile_modules.py script

---

modules_compilation/run_module_compilation.sh

Reduce RAM usage to avoid killing k8s pods.

fix: reduce number of parallel module compilations
